[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.97.3"

[functions]
  directory = "./functions"

[[redirects]]
  from = "/blog/"
  to = "https://www.infinyon.com/blog/"
  status = 301
  force = true

[[redirects]]
from = "/docs/smartmodules/"
to = "/smartmodules/"
status = 301
force = true

[[redirects]]
from = "/docs/smartmodules/quick-start/"
to = "/smartmodules/"
status = 301
force = true

[[redirects]]
from = "/docs/smartmodules/filter/"
to = "/smartmodules/transform/filter/"
status = 301
force = true

[[redirects]]
from = "/docs/smartmodules/map/"
to = "/smartmodules/transform/map/"
status = 301
force = true

[[redirects]]
from = "/docs/smartmodules/array-map/"
to = "/smartmodules/transform/array-map/"
status = 301
force = true

[[redirects]]
from = "/docs/smartmodules/aggregate/"
to = "/smartmodules/analytics/aggregate/"
status = 301
force = true
